import Head from 'next/head'
import { RandomFox } from '@/components/RandomFox'
import { useState } from 'react';

// generate a random funtion between 1 and 123
const random = () => Math.floor(Math.random() * 123) + 1;

// generate a random funtion between 1 and 123
const generateId = () => Math.random().toString().substr(2,9);

type ImageItem = {id:string ; url:string}

export default function Home() {
  const [images, setImages] = useState<Array<ImageItem>>([
    {id:generateId(),url:`https://randomfox.ca/images/${random()}.jpg`},
    {id:generateId(),url:`https://randomfox.ca/images/${random()}.jpg`},
    {id:generateId(),url:`https://randomfox.ca/images/${random()}.jpg`},
    {id:generateId(),url:`https://randomfox.ca/images/${random()}.jpg`},
    {id:generateId(),url:`https://randomfox.ca/images/${random()}.jpg`},
  ])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        {images.map(({id,url})=>(
          <div key={id} className="p-4">
            <RandomFox image={url}/> 
          </div>
        ))

        }
        
      </main>

      <footer>

      </footer>
    </>
  )
}
